version: '3.8'

services:
  web:
    build:
      context: . 
      dockerfile: Dockerfile 
    container_name: api_banco_web 
    # command: >
    #   sh -c "python manage.py migrate --noinput &&
    #          gunicorn banco_project.wsgi:application --bind 0.0.0.0:8000 --workers 2 --threads 2 --worker-tmp-dir /dev/shm"
    command: /app/entrypoint.sh
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8001:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env 

  db:
    image: postgres:15-alpine
    container_name: api_banco_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"

volumes:
  postgres_data:
  static_volume: