[tool.black]
line-length = 88
target-version = ['py311'] # Especifique a versão do Python que você está usando (ex: py311 para Python 3.11)
# include = '\.pyi?$'
# exclude = '''
# /(
#     \.eggs
#   | \.git
#   | \.hg
#   | \.mypy_cache
#   | \.tox
#   | \.venv
#   | _build
#   | buck-out
#   | build
#   | dist
#   | migrations
# )/
# '''