# Generated by Django 5.2 on 2025-05-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contabancaria",
            name="numero_conta",
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name="transacao",
            name="tipo",
            field=models.CharField(max_length=10),
        ),
    ]
